services:

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "26439:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - open-webui-data:/app/backend/data

  mcp-github:
    image: ghcr.io/github/github-mcp-server:latest
    container_name: mcp-github
    restart: unless-stopped
    environment:
      GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN}
    stdin_open: true
    tty: true

  mcp-atlassian-confluence:
    image: ghcr.io/sooperset/mcp-atlassian:latest
    container_name: mcp-atlassian-confluence
    restart: unless-stopped
    ports:
      - "37462:8000"
    environment:
      CONFLUENCE_URL: ${CONFLUENCE_URL}
      CONFLUENCE_PERSONAL_TOKEN: ${CONFLUENCE_PERSONAL_TOKEN}
      MCP_VERBOSE: true
    command: ["--transport", "sse"]

  mcp-slack:
    image: mcp/slack:latest
    container_name: mcp-slack
    restart: unless-stopped
    environment:
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_TEAM_ID: ${SLACK_TEAM_ID}
      MCP_VERBOSE: true
    stdin_open: true
    tty: true

volumes:
  open-webui-data:
