FROM node:lts-alpine

WORKDIR /app

RUN apk add --no-cache git
RUN git clone https://github.com/cgoinglove/mcp-client-chatbot.git .

RUN npm install -g pnpm
RUN pnpm install

EXPOSE 3000

CMD ["sh", "-c", "pnpm db:migrate && pnpm dev"]
